sudo: required

services:
  - docker

install:
  - docker-compose build build-frontend

script:
  - docker-compose run --rm build-backend
  - docker-compose run --rm build-frontend
  - docker-compose run integration-test

after_script:
  - docker-compose down
