version: '3'
services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: "ayush"
      POSTGRES_DB: "asset-wizard"
  backend:
    build: ./backend
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/asset-wizard"
    depends_on:
      - db
