# run `docker-compose up` and access to http://localhost:8080/

version: '3'
services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: "ayush"
      POSTGRES_DB: "asset-wizard"
  backend:
    build: ./backend
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/asset-wizard"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - backend
